//Launch chrome browser

Log "Launching Chrome"
put "chrome_icon1" into global chrome_icon
DoubleClick "chrome_icon"
WaitFor 20, text:"Search Google or type a URL"

//Put "" into global search_var
TypeText "demo.nopcommerce.com",Return
Waitfor 20, text:"Welcome to our store"

//put "Digital downloads" into global digital_downloads_navBar

//click 
Click text:"Digital downloads"
WaitFor 20, text:"Sort by"


Click {Image:"click_dropdown", WaitFor:10.2},Tab
waitfor 10
Click text:"Name A to Z"
